# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Saftmakaren_Prototype.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 948)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.removeRecipe_PB = QtWidgets.QPushButton(self.frame_2)
        self.removeRecipe_PB.setObjectName("removeRecipe_PB")
        self.horizontalLayout.addWidget(self.removeRecipe_PB)
        self.newRecipe_PB = QtWidgets.QPushButton(self.frame_2)
        self.newRecipe_PB.setObjectName("newRecipe_PB")
        self.horizontalLayout.addWidget(self.newRecipe_PB)
        self.editRecipe_PB = QtWidgets.QPushButton(self.frame_2)
        self.editRecipe_PB.setObjectName("editRecipe_PB")
        self.horizontalLayout.addWidget(self.editRecipe_PB)
        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.recipeName_LE = QtWidgets.QLineEdit(self.frame_2)
        self.recipeName_LE.setObjectName("recipeName_LE")
        self.gridLayout_3.addWidget(self.recipeName_LE, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 7, 1, 1)
        self.description_LE = QtWidgets.QLineEdit(self.frame_2)
        self.description_LE.setObjectName("description_LE")
        self.gridLayout_3.addWidget(self.description_LE, 1, 2, 1, 1)
        self.boilTime_LE = QtWidgets.QLineEdit(self.frame_2)
        self.boilTime_LE.setObjectName("boilTime_LE")
        self.gridLayout_3.addWidget(self.boilTime_LE, 0, 6, 1, 1)
        self.scrapChanges_PB = QtWidgets.QPushButton(self.frame_2)
        self.scrapChanges_PB.setObjectName("scrapChanges_PB")
        self.gridLayout_3.addWidget(self.scrapChanges_PB, 1, 6, 1, 1)
        self.save_Recipe_PB = QtWidgets.QPushButton(self.frame_2)
        self.save_Recipe_PB.setObjectName("save_Recipe_PB")
        self.gridLayout_3.addWidget(self.save_Recipe_PB, 1, 8, 1, 1)
        self.RecipesTree = QtWidgets.QTreeWidget(self.frame_2)
        self.RecipesTree.setMaximumSize(QtCore.QSize(300, 16777215))
        self.RecipesTree.setObjectName("RecipesTree")
        self.gridLayout_3.addWidget(self.RecipesTree, 2, 0, 1, 1)
        self.efficiency_LE = QtWidgets.QLineEdit(self.frame_2)
        self.efficiency_LE.setObjectName("efficiency_LE")
        self.gridLayout_3.addWidget(self.efficiency_LE, 0, 8, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 1, 1, 1)
        self.RecipeList_LB = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RecipeList_LB.setFont(font)
        self.RecipeList_LB.setAlignment(QtCore.Qt.AlignCenter)
        self.RecipeList_LB.setObjectName("RecipeList_LB")
        self.gridLayout_3.addWidget(self.RecipeList_LB, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 5, 1, 1)
        self.batchSize_LE = QtWidgets.QLineEdit(self.frame_2)
        self.batchSize_LE.setObjectName("batchSize_LE")
        self.gridLayout_3.addWidget(self.batchSize_LE, 0, 4, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 190, 301, 167))
        self.groupBox_3.setObjectName("groupBox_3")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 10, 301, 151))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 281, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_2.addWidget(self.label_26)
        self.startThickness_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.startThickness_LE.setObjectName("startThickness_LE")
        self.horizontalLayout_2.addWidget(self.startThickness_LE)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_2.addWidget(self.label_29)
        self.mashTime_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.mashTime_LE.setObjectName("mashTime_LE")
        self.horizontalLayout_2.addWidget(self.mashTime_LE)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_3.addWidget(self.label_27)
        self.mashTemp_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.mashTemp_LE.setObjectName("mashTemp_LE")
        self.horizontalLayout_3.addWidget(self.mashTemp_LE)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_3.addWidget(self.label_28)
        self.mashAmount_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.mashAmount_LE.setObjectName("mashAmount_LE")
        self.horizontalLayout_3.addWidget(self.mashAmount_LE)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_4.setGeometry(QtCore.QRect(344, 235, 221, 271))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 370, 291, 166))
        self.groupBox_5.setObjectName("groupBox_5")
        self.frame_5 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_5.setGeometry(QtCore.QRect(-1, 9, 291, 151))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 30, 231, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_4.addWidget(self.label_30)
        self.method_LE = QtWidgets.QLineEdit(self.layoutWidget1)
        self.method_LE.setObjectName("method_LE")
        self.horizontalLayout_4.addWidget(self.method_LE)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_4.addWidget(self.label_31)
        self.primeTemp_Le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.primeTemp_Le.setObjectName("primeTemp_Le")
        self.horizontalLayout_4.addWidget(self.primeTemp_Le)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_5.addWidget(self.label_32)
        self.co2Level_LE = QtWidgets.QLineEdit(self.layoutWidget1)
        self.co2Level_LE.setObjectName("co2Level_LE")
        self.horizontalLayout_5.addWidget(self.co2Level_LE)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_5.addWidget(self.label_33)
        self.primeAmount_LE = QtWidgets.QLineEdit(self.layoutWidget1)
        self.primeAmount_LE.setObjectName("primeAmount_LE")
        self.horizontalLayout_5.addWidget(self.primeAmount_LE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_6.setGeometry(QtCore.QRect(590, 230, 381, 301))
        self.groupBox_6.setObjectName("groupBox_6")
        self.modifiedHco3_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.modifiedHco3_LE.setGeometry(QtCore.QRect(340, 70, 41, 20))
        self.modifiedHco3_LE.setObjectName("modifiedHco3_LE")
        self.modifiedCa2_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.modifiedCa2_LE.setGeometry(QtCore.QRect(90, 70, 41, 20))
        self.modifiedCa2_LE.setObjectName("modifiedCa2_LE")
        self.modifiedMg2_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.modifiedMg2_LE.setGeometry(QtCore.QRect(140, 70, 41, 20))
        self.modifiedMg2_LE.setObjectName("modifiedMg2_LE")
        self.modifiedNa_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.modifiedNa_LE.setGeometry(QtCore.QRect(190, 70, 41, 20))
        self.modifiedNa_LE.setObjectName("modifiedNa_LE")
        self.modifiedCl_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.modifiedCl_LE.setGeometry(QtCore.QRect(240, 70, 41, 20))
        self.modifiedCl_LE.setObjectName("modifiedCl_LE")
        self.modifiedSo42_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.modifiedSo42_LE.setGeometry(QtCore.QRect(290, 70, 41, 20))
        self.modifiedSo42_LE.setObjectName("modifiedSo42_LE")
        self.mineralsAdd_PB = QtWidgets.QPushButton(self.groupBox_6)
        self.mineralsAdd_PB.setGeometry(QtCore.QRect(260, 140, 51, 21))
        self.mineralsAdd_PB.setObjectName("mineralsAdd_PB")
        self.waterAmount_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.waterAmount_LE.setGeometry(QtCore.QRect(20, 140, 61, 20))
        self.waterAmount_LE.setObjectName("waterAmount_LE")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(20, 120, 51, 21))
        self.label_17.setObjectName("label_17")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.groupBox_6)
        self.treeWidget_2.setGeometry(QtCore.QRect(90, 140, 161, 21))
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(20, 40, 71, 21))
        self.label_18.setObjectName("label_18")
        self.sourceHco3_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.sourceHco3_LE.setGeometry(QtCore.QRect(340, 40, 41, 20))
        self.sourceHco3_LE.setObjectName("sourceHco3_LE")
        self.sourceCa2_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.sourceCa2_LE.setGeometry(QtCore.QRect(90, 40, 41, 20))
        self.sourceCa2_LE.setObjectName("sourceCa2_LE")
        self.sourceMg2_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.sourceMg2_LE.setGeometry(QtCore.QRect(140, 40, 41, 20))
        self.sourceMg2_LE.setObjectName("sourceMg2_LE")
        self.sourceNa_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.sourceNa_LE.setGeometry(QtCore.QRect(190, 40, 41, 20))
        self.sourceNa_LE.setObjectName("sourceNa_LE")
        self.sourceCl_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.sourceCl_LE.setGeometry(QtCore.QRect(240, 40, 41, 20))
        self.sourceCl_LE.setObjectName("sourceCl_LE")
        self.sourceSo42_LE = QtWidgets.QLineEdit(self.groupBox_6)
        self.sourceSo42_LE.setGeometry(QtCore.QRect(290, 40, 41, 20))
        self.sourceSo42_LE.setObjectName("sourceSo42_LE")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(20, 70, 41, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(90, 20, 41, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(140, 20, 41, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(190, 20, 41, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(240, 20, 41, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(290, 20, 41, 21))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(340, 20, 41, 21))
        self.label_25.setObjectName("label_25")
        self.mineralsRemove_PB = QtWidgets.QPushButton(self.groupBox_6)
        self.mineralsRemove_PB.setGeometry(QtCore.QRect(320, 170, 51, 21))
        self.mineralsRemove_PB.setObjectName("mineralsRemove_PB")
        self.mineralsListWidget = QtWidgets.QListWidget(self.groupBox_6)
        self.mineralsListWidget.setGeometry(QtCore.QRect(20, 170, 261, 121))
        self.mineralsListWidget.setObjectName("mineralsListWidget")
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_7.setGeometry(QtCore.QRect(640, 20, 321, 191))
        self.groupBox_7.setObjectName("groupBox_7")
        self.otherAmount_LE = QtWidgets.QLineEdit(self.groupBox_7)
        self.otherAmount_LE.setGeometry(QtCore.QRect(10, 40, 61, 20))
        self.otherAmount_LE.setObjectName("otherAmount_LE")
        self.otherName_LE = QtWidgets.QLineEdit(self.groupBox_7)
        self.otherName_LE.setGeometry(QtCore.QRect(80, 40, 71, 20))
        self.otherName_LE.setObjectName("otherName_LE")
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(80, 20, 51, 21))
        self.label_16.setObjectName("label_16")
        self.otherAdd_PB = QtWidgets.QPushButton(self.groupBox_7)
        self.otherAdd_PB.setGeometry(QtCore.QRect(240, 40, 51, 21))
        self.otherAdd_PB.setObjectName("otherAdd_PB")
        self.otherRemove_PB = QtWidgets.QPushButton(self.groupBox_7)
        self.otherRemove_PB.setGeometry(QtCore.QRect(250, 70, 51, 21))
        self.otherRemove_PB.setObjectName("otherRemove_PB")
        self.otherListWidget = QtWidgets.QListWidget(self.groupBox_7)
        self.otherListWidget.setGeometry(QtCore.QRect(20, 70, 191, 111))
        self.otherListWidget.setObjectName("otherListWidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 10, 331, 200))
        self.groupBox_2.setObjectName("groupBox_2")
        self.frame_6 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_6.setGeometry(QtCore.QRect(9, 9, 321, 191))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 231, 20))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 50, 271, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.hopAmount_LE = QtWidgets.QLineEdit(self.layoutWidget3)
        self.hopAmount_LE.setObjectName("hopAmount_LE")
        self.horizontalLayout_6.addWidget(self.hopAmount_LE)
        self.hopName_LE = QtWidgets.QLineEdit(self.layoutWidget3)
        self.hopName_LE.setObjectName("hopName_LE")
        self.horizontalLayout_6.addWidget(self.hopName_LE)
        self.hopTime_LE = QtWidgets.QLineEdit(self.layoutWidget3)
        self.hopTime_LE.setObjectName("hopTime_LE")
        self.horizontalLayout_6.addWidget(self.hopTime_LE)
        self.AA_LE = QtWidgets.QLineEdit(self.layoutWidget3)
        self.AA_LE.setObjectName("AA_LE")
        self.horizontalLayout_6.addWidget(self.AA_LE)
        self.hopAdd_PB = QtWidgets.QPushButton(self.layoutWidget3)
        self.hopAdd_PB.setObjectName("hopAdd_PB")
        self.horizontalLayout_6.addWidget(self.hopAdd_PB)
        self.layoutWidget4 = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 80, 311, 101))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.hopListWidget = QtWidgets.QListWidget(self.layoutWidget4)
        self.hopListWidget.setObjectName("hopListWidget")
        self.horizontalLayout_8.addWidget(self.hopListWidget)
        self.hopRemove_PB = QtWidgets.QPushButton(self.layoutWidget4)
        self.hopRemove_PB.setObjectName("hopRemove_PB")
        self.horizontalLayout_8.addWidget(self.hopRemove_PB)
        self.groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 291, 181))
        self.groupBox.setObjectName("groupBox")
        self.frame_7 = QtWidgets.QFrame(self.groupBox)
        self.frame_7.setGeometry(QtCore.QRect(10, 10, 281, 171))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.layoutWidget5 = QtWidgets.QWidget(self.frame_7)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 40, 281, 25))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ferAmount_LE = QtWidgets.QLineEdit(self.layoutWidget5)
        self.ferAmount_LE.setObjectName("ferAmount_LE")
        self.horizontalLayout_9.addWidget(self.ferAmount_LE)
        self.ferName_LE = QtWidgets.QLineEdit(self.layoutWidget5)
        self.ferName_LE.setObjectName("ferName_LE")
        self.horizontalLayout_9.addWidget(self.ferName_LE)
        self.lovibond_LE = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lovibond_LE.setObjectName("lovibond_LE")
        self.horizontalLayout_9.addWidget(self.lovibond_LE)
        self.ferAdd_PB = QtWidgets.QPushButton(self.layoutWidget5)
        self.ferAdd_PB.setObjectName("ferAdd_PB")
        self.horizontalLayout_9.addWidget(self.ferAdd_PB)
        self.layoutWidget6 = QtWidgets.QWidget(self.frame_7)
        self.layoutWidget6.setGeometry(QtCore.QRect(0, 20, 201, 21))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.layoutWidget7 = QtWidgets.QWidget(self.frame_7)
        self.layoutWidget7.setGeometry(QtCore.QRect(0, 70, 281, 91))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ferListWidget = QtWidgets.QListWidget(self.layoutWidget7)
        self.ferListWidget.setObjectName("ferListWidget")
        self.horizontalLayout_11.addWidget(self.ferListWidget)
        self.ferRemove_PB = QtWidgets.QPushButton(self.layoutWidget7)
        self.ferRemove_PB.setObjectName("ferRemove_PB")
        self.horizontalLayout_11.addWidget(self.ferRemove_PB)
        self.gridLayout_3.addWidget(self.frame_3, 2, 1, 2, 8)
        self.gridLayout.addWidget(self.frame_2, 3, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.username_LB = QtWidgets.QLabel(self.frame)
        self.username_LB.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.username_LB.setFont(font)
        self.username_LB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.username_LB.setObjectName("username_LB")
        self.gridLayout_2.addWidget(self.username_LB, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(200, 200))
        self.graphicsView.setMaximumSize(QtCore.QSize(200, 200))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1278, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.removeRecipe_PB.setText(_translate("MainWindow", "Remove Recipe"))
        self.newRecipe_PB.setText(_translate("MainWindow", "New Recipe"))
        self.editRecipe_PB.setText(_translate("MainWindow", "Edit Recipe"))
        self.label_5.setText(_translate("MainWindow", "BatchSize:"))
        self.label_3.setText(_translate("MainWindow", "Recipe Name:"))
        self.label_7.setText(_translate("MainWindow", "Efficiency:"))
        self.scrapChanges_PB.setText(_translate("MainWindow", "Scrap Changes"))
        self.save_Recipe_PB.setText(_translate("MainWindow", "Save"))
        self.RecipesTree.headerItem().setText(0, _translate("MainWindow", "#"))
        self.RecipesTree.headerItem().setText(1, _translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Description:"))
        self.RecipeList_LB.setText(_translate("MainWindow", "Recipe List"))
        self.label_6.setText(_translate("MainWindow", "Boil Time:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Mash Guidelines"))
        self.label_26.setText(_translate("MainWindow", "Starting Thickness"))
        self.label_29.setText(_translate("MainWindow", "Time"))
        self.label_27.setText(_translate("MainWindow", "Temp"))
        self.label_28.setText(_translate("MainWindow", "Amount"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Yeast"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Priming Information"))
        self.label_30.setText(_translate("MainWindow", "Method"))
        self.label_31.setText(_translate("MainWindow", "Temp"))
        self.label_32.setText(_translate("MainWindow", "CO2 Level"))
        self.label_33.setText(_translate("MainWindow", "Amount"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Water Chemistry"))
        self.mineralsAdd_PB.setText(_translate("MainWindow", "Add"))
        self.label_17.setText(_translate("MainWindow", "Amount"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "Minerals"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("MainWindow", "Calcium  Chloride"))
        self.treeWidget_2.topLevelItem(1).setText(0, _translate("MainWindow", "Chalk"))
        self.treeWidget_2.topLevelItem(2).setText(0, _translate("MainWindow", "Epsom Salt"))
        self.treeWidget_2.topLevelItem(3).setText(0, _translate("MainWindow", "Gypsum"))
        self.treeWidget_2.topLevelItem(4).setText(0, _translate("MainWindow", "Magnesium Chloride"))
        self.treeWidget_2.topLevelItem(5).setText(0, _translate("MainWindow", "Baking Soda"))
        self.treeWidget_2.topLevelItem(6).setText(0, _translate("MainWindow", "Citric Acid"))
        self.treeWidget_2.topLevelItem(7).setText(0, _translate("MainWindow", "Lactic Acid"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_18.setText(_translate("MainWindow", "Source water"))
        self.label_19.setText(_translate("MainWindow", "Modified"))
        self.label_20.setText(_translate("MainWindow", "Ca+2"))
        self.label_21.setText(_translate("MainWindow", "Mg+2"))
        self.label_22.setText(_translate("MainWindow", "Na+"))
        self.label_23.setText(_translate("MainWindow", "Cl-"))
        self.label_24.setText(_translate("MainWindow", "SO4-2"))
        self.label_25.setText(_translate("MainWindow", "HCO3-"))
        self.mineralsRemove_PB.setText(_translate("MainWindow", "Remove"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Other"))
        self.label_15.setText(_translate("MainWindow", "Amount"))
        self.label_16.setText(_translate("MainWindow", "Name"))
        self.otherAdd_PB.setText(_translate("MainWindow", "Add"))
        self.otherRemove_PB.setText(_translate("MainWindow", "Remove"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Hops"))
        self.label_11.setText(_translate("MainWindow", "Amount"))
        self.label_12.setText(_translate("MainWindow", "Name"))
        self.label_14.setText(_translate("MainWindow", "Time"))
        self.label_13.setText(_translate("MainWindow", "AA"))
        self.hopAdd_PB.setText(_translate("MainWindow", "Add"))
        self.hopRemove_PB.setText(_translate("MainWindow", "Remove"))
        self.groupBox.setTitle(_translate("MainWindow", "Fermentables"))
        self.ferAdd_PB.setText(_translate("MainWindow", "Add"))
        self.label_8.setText(_translate("MainWindow", "Amount"))
        self.label_9.setText(_translate("MainWindow", "Name"))
        self.label_10.setText(_translate("MainWindow", "Lovibond"))
        self.ferRemove_PB.setText(_translate("MainWindow", "Remove"))
        self.username_LB.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Saftmakaren"))

