# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Saftmakaren_Prototype.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 948)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(200, 200))
        self.graphicsView.setMaximumSize(QtCore.QSize(200, 200))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.RecipeList_LB = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RecipeList_LB.setFont(font)
        self.RecipeList_LB.setAlignment(QtCore.Qt.AlignCenter)
        self.RecipeList_LB.setObjectName("RecipeList_LB")
        self.gridLayout_3.addWidget(self.RecipeList_LB, 0, 0, 3, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 8, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 6, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.frame_2)
        self.treeWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout_3.addWidget(self.treeWidget, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 0, 6, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 1, 2, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 0, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 5, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 0, 8, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 976, 552))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 301, 181))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(60, 40, 101, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(170, 40, 41, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 40, 41, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setGeometry(QtCore.QRect(10, 70, 211, 101))
        self.listView.setObjectName("listView")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(70, 20, 71, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(170, 20, 47, 13))
        self.label_10.setObjectName("label_10")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 40, 51, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(230, 70, 51, 21))
        self.pushButton_10.setObjectName("pushButton_10")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 20, 301, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.listView_2 = QtWidgets.QListView(self.groupBox_2)
        self.listView_2.setGeometry(QtCore.QRect(10, 70, 221, 101))
        self.listView_2.setObjectName("listView_2")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 40, 41, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(70, 40, 51, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(190, 40, 41, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(70, 20, 31, 20))
        self.label_12.setObjectName("label_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 40, 51, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(200, 20, 31, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(130, 40, 51, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(130, 20, 31, 20))
        self.label_14.setObjectName("label_14")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_9.setGeometry(QtCore.QRect(240, 70, 51, 21))
        self.pushButton_9.setObjectName("pushButton_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 210, 301, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 360, 251, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setGeometry(QtCore.QRect(280, 360, 251, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setGeometry(QtCore.QRect(560, 210, 401, 291))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_15.setGeometry(QtCore.QRect(340, 70, 41, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_16.setGeometry(QtCore.QRect(90, 70, 41, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_17.setGeometry(QtCore.QRect(140, 70, 41, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_18.setGeometry(QtCore.QRect(190, 70, 41, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_19.setGeometry(QtCore.QRect(240, 70, 41, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_20.setGeometry(QtCore.QRect(290, 70, 41, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_7.setGeometry(QtCore.QRect(260, 140, 51, 21))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_21.setGeometry(QtCore.QRect(20, 140, 61, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(20, 120, 51, 21))
        self.label_17.setObjectName("label_17")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.groupBox_6)
        self.treeWidget_2.setGeometry(QtCore.QRect(90, 140, 161, 21))
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        self.listView_4 = QtWidgets.QListView(self.groupBox_6)
        self.listView_4.setGeometry(QtCore.QRect(20, 170, 291, 101))
        self.listView_4.setObjectName("listView_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(20, 40, 71, 21))
        self.label_18.setObjectName("label_18")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_22.setGeometry(QtCore.QRect(340, 40, 41, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_23.setGeometry(QtCore.QRect(90, 40, 41, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_24.setGeometry(QtCore.QRect(140, 40, 41, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_25.setGeometry(QtCore.QRect(190, 40, 41, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_26.setGeometry(QtCore.QRect(240, 40, 41, 20))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_27.setGeometry(QtCore.QRect(290, 40, 41, 20))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(20, 70, 41, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(90, 20, 41, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(140, 20, 41, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(190, 20, 41, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(240, 20, 41, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(290, 20, 41, 21))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(340, 20, 41, 21))
        self.label_25.setObjectName("label_25")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_11.setGeometry(QtCore.QRect(320, 170, 51, 21))
        self.pushButton_11.setObjectName("pushButton_11")
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setGeometry(QtCore.QRect(650, 20, 311, 181))
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 40, 61, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_13.setGeometry(QtCore.QRect(80, 40, 71, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(80, 20, 51, 21))
        self.label_16.setObjectName("label_16")
        self.listView_3 = QtWidgets.QListView(self.groupBox_7)
        self.listView_3.setGeometry(QtCore.QRect(10, 70, 231, 101))
        self.listView_3.setObjectName("listView_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_6.setGeometry(QtCore.QRect(240, 40, 51, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_8.setGeometry(QtCore.QRect(250, 70, 51, 21))
        self.pushButton_8.setObjectName("pushButton_8")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 2, 1, 2, 8)
        self.gridLayout.addWidget(self.frame_2, 3, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1278, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Saftmakaren"))
        self.RecipeList_LB.setText(_translate("MainWindow", "Recipe List"))
        self.pushButton.setText(_translate("MainWindow", "Save"))
        self.pushButton_2.setText(_translate("MainWindow", "Scrap Changes"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Edit"))
        self.label_3.setText(_translate("MainWindow", "Recipe Name:"))
        self.label_5.setText(_translate("MainWindow", "BatchSize:"))
        self.label_4.setText(_translate("MainWindow", "Description:"))
        self.label_7.setText(_translate("MainWindow", "Efficiency:"))
        self.label_6.setText(_translate("MainWindow", "Boil Time:"))
        self.groupBox.setTitle(_translate("MainWindow", "Fermentables"))
        self.label_8.setText(_translate("MainWindow", "Ammount"))
        self.label_9.setText(_translate("MainWindow", "Name"))
        self.label_10.setText(_translate("MainWindow", "Lovibond"))
        self.pushButton_5.setText(_translate("MainWindow", "Add"))
        self.pushButton_10.setText(_translate("MainWindow", "Remove"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Hops"))
        self.label_11.setText(_translate("MainWindow", "Ammount"))
        self.label_12.setText(_translate("MainWindow", "Name"))
        self.pushButton_4.setText(_translate("MainWindow", "Add"))
        self.label_13.setText(_translate("MainWindow", "AA"))
        self.label_14.setText(_translate("MainWindow", "Time"))
        self.pushButton_9.setText(_translate("MainWindow", "Remove"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Mash Guidelines"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Yeast"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Priming Information"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Water Chemistry"))
        self.pushButton_7.setText(_translate("MainWindow", "Add"))
        self.label_17.setText(_translate("MainWindow", "Ammount"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "Minerals"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("MainWindow", "Calcium  Chloride"))
        self.treeWidget_2.topLevelItem(1).setText(0, _translate("MainWindow", "Chalk"))
        self.treeWidget_2.topLevelItem(2).setText(0, _translate("MainWindow", "Epsom Salt"))
        self.treeWidget_2.topLevelItem(3).setText(0, _translate("MainWindow", "Gypsum"))
        self.treeWidget_2.topLevelItem(4).setText(0, _translate("MainWindow", "Magnesium Chloride"))
        self.treeWidget_2.topLevelItem(5).setText(0, _translate("MainWindow", "Baking Soda"))
        self.treeWidget_2.topLevelItem(6).setText(0, _translate("MainWindow", "Citric Acid"))
        self.treeWidget_2.topLevelItem(7).setText(0, _translate("MainWindow", "Lactic Acid"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_18.setText(_translate("MainWindow", "Source water"))
        self.label_19.setText(_translate("MainWindow", "Modified"))
        self.label_20.setText(_translate("MainWindow", "Ca+2"))
        self.label_21.setText(_translate("MainWindow", "Mg+2"))
        self.label_22.setText(_translate("MainWindow", "Na+"))
        self.label_23.setText(_translate("MainWindow", "Cl-"))
        self.label_24.setText(_translate("MainWindow", "SO4-2"))
        self.label_25.setText(_translate("MainWindow", "HCO3-"))
        self.pushButton_11.setText(_translate("MainWindow", "Remove"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Other"))
        self.label_15.setText(_translate("MainWindow", "Ammount"))
        self.label_16.setText(_translate("MainWindow", "Name"))
        self.pushButton_6.setText(_translate("MainWindow", "Add"))
        self.pushButton_8.setText(_translate("MainWindow", "Remove"))

